import type { Metadata } from "next";
import "./globals.css";
import { Header } from "./components/header/header";

export const metadata: Metadata = {
  title: "Portifolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex flex-col items-center py-4">
      <Header />
        <main className="flex min-h-screen flex-col items-center px-4  bg-zinc-900 my-4 mx-2 w-full md:w-4/6 xl:max-w-screen-sm  rounded-xl gap-8">
         {children}
        </main>
      </body>
    </html>
  );
}


