import type { Metadata } from "next";
import "./globals.css";
import { Header } from "./components/header/header";
import Nav from "./components/Nav/page";
import Footer from "./components/Footer";

export const metadata: Metadata = {
  title: "Portifolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex flex-col items-center justify-center py-4 gap-4 sm:w-full">
      <Header />
        <main className="flex min-h-screen sm:w-auto flex-col items-center  px-4 py-4  bg-zinc-900 mx-2 md:w-4/6 xl:max-w-screen-sm  rounded-xl gap-6">
        <Nav />
         {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}


